### ISSUE TITLE
Stablize Releases

### ISSUE THREAD

**Issue by SISheogorath** [codimd/cli#25]
Since the CLI is now already existing for quite a while and working great for most people, we might want to start to tag releases.

Background: In order to package it for any regular distro, we would need to provide versions. I don't plan do package it, but it's required to enable people to do that and iirc there is an AUR package already existing.

Also: It makes it easier to announce new features and, given we ever have to introduce breaking changes on CodiMD-side, we can tell which CLI version works with what CodiMD version.

I'll leave it to you if you want to use 0.x.x versions (i.e. unstable) or if you want to switch to 1.0.0 for a first version. As I don't think it makes a lot of sense to use anything else than [SemVer](https://semver.org/) in here.

**Comment by davidak** [comment]
Yes, please tag stable releases! I would like to package it for NixOS.

> iirc there is an AUR package already existing

yes, it's about a year old. releases might notify people to update what provides better experience for users :)

https://repology.org/project/codimd-cli/versions

**Comment by pirate** [comment]
Depending on compatibility across forks and feature set, it might make sense to use https://github.com/hackmdio/codimd-cli instead for your Nix package @davidak. (more discussion  in #34 )

**Comment by pirate** [comment]
Done: https://github.com/codimd/cli/releases
