### ISSUE TITLE
Fix import command returning redirect message instead of note id

### ISSUE THREAD

**Issue by davidak** [codimd/cli#31]
```
Options:
    $ codimd import /path/to/your/content.md
    qhmNmwmxSmK1H2oJmkKBQQ       # returns note id on success
```

but the actual output is

`Found. Redirecting to https://pad.nixnet.services/yN-Ji4YeTNaZuhci23IsFQ`

**Comment by pirate** [comment]
I think rather than change the docs it would be better to fix the output so that it returns the note id correctly.

However, see #34 as I'm not sure we'll be continuing development on this project long-term.

**Comment by davidak** [comment]
I think the URL is more useful to work with later. But that would be a breaking change. Maybe make a 0.1 release now and change it and mention it in the release notes of 0.2.

Related issue: https://github.com/codimd/cli/issues/33

**Comment by pirate** [comment]
The reason I decided against URL in favor of just the path is that it's easier to add the path to `$CODIMD_SERVER` yourself than to remove the `$CODIMD_SERVER` prefix from the output.  Also we run one server listening on many domains simultaneously, so we use those paths independent of whatever domain the server happens to be accessed from.

**Comment by pirate** [comment]
Fixed in https://github.com/codimd/cli/commit/83d913ef468d738a2f1bd44c1d90b29ff8e6a4d5
