### ISSUE TITLE
Output just URL of imported note

### ISSUE THREAD

**Issue by davidak** [codimd/cli#33]
According to the unix philosophy, you should be able to pipe the output of a tool into another. With the output of this script, it is not possible.

The actual output of `./codimd import test.md` is

`Found. Redirecting to https://pad.nixnet.services/gNvbypueQ6awH73V3nx_jw`

(don't forget to update usage information when this is changed)

## Workaround

Use awk to manipulate the text:

```
./codimd import test.md | awk '{print $4}'
https://pad.nixnet.services/zKOoDxhQTuaT4dnJAybrfw
```

**Comment by pirate** [comment]
This is a bug, not an interntional design, see #31.
