### ISSUE TITLE
Document login behavior

### ISSUE THREAD

**Issue by davidak** [codimd/cli#35]
I logged in with my account yesterday. Then i imported notes today. I noticed that i was not able to edit permissions. I didn't own the notes! So it seems i was not logged in anymore. (that might also be related to the fact that i deleted my account multiple times)

Please document if you have to login after some time again.

**Comment by pirate** [comment]
You should not need to log in multiple times, that's a bug or configuration issue.

Your session cookie is written to `$CODIMD_COOKIES_FILE` (which defaults to `~/.codimd-key.conf`).

You may need to log in again if:
 - your session expired
 - the codimd server was restarted (which force-expires all sessions as a side-effect)
 - the  is`$CODIMD_COOKIES_FILE` deleted, moved, or becomes unreadable by `codimd-cli`

If none of those things happened, then it's probably a bug that we should investigate. If you think it's a bug and you're able to reproduce it consistently, then comment back here with your "steps to reproduce" and environment details and I'll reopen the ticket.

**Comment by davidak** [comment]
It was probably because i deleted my account (to delete all notes and import again) and created a new one with same credentials. When a session is saved instead of the crentials, it's no surprise that it don't work anymore.

Can you add the information when a user has to login again (and how to check if still logged in) to the documentation? A random issue is not a good place for documentation.

**Comment by pirate** [comment]
Done: https://github.com/codimd/cli/commit/69c5a456443a4ff6cb994775a1f4bc96698089eb
